// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoc/hello.proto

#ifndef PROTOBUF_INCLUDED_protoc_2fhello_2eproto
#define PROTOBUF_INCLUDED_protoc_2fhello_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_protoc_2fhello_2eproto 

namespace protobuf_protoc_2fhello_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_protoc_2fhello_2eproto
class HelloWorldRequest;
class HelloWorldRequestDefaultTypeInternal;
extern HelloWorldRequestDefaultTypeInternal _HelloWorldRequest_default_instance_;
class HelloWorldResponse;
class HelloWorldResponseDefaultTypeInternal;
extern HelloWorldResponseDefaultTypeInternal _HelloWorldResponse_default_instance_;
namespace google {
namespace protobuf {
template<> ::HelloWorldRequest* Arena::CreateMaybeMessage<::HelloWorldRequest>(Arena*);
template<> ::HelloWorldResponse* Arena::CreateMaybeMessage<::HelloWorldResponse>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class HelloWorldRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:HelloWorldRequest) */ {
 public:
  HelloWorldRequest();
  virtual ~HelloWorldRequest();

  HelloWorldRequest(const HelloWorldRequest& from);

  inline HelloWorldRequest& operator=(const HelloWorldRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HelloWorldRequest(HelloWorldRequest&& from) noexcept
    : HelloWorldRequest() {
    *this = ::std::move(from);
  }

  inline HelloWorldRequest& operator=(HelloWorldRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const HelloWorldRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HelloWorldRequest* internal_default_instance() {
    return reinterpret_cast<const HelloWorldRequest*>(
               &_HelloWorldRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(HelloWorldRequest* other);
  friend void swap(HelloWorldRequest& a, HelloWorldRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HelloWorldRequest* New() const final {
    return CreateMaybeMessage<HelloWorldRequest>(NULL);
  }

  HelloWorldRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<HelloWorldRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const HelloWorldRequest& from);
  void MergeFrom(const HelloWorldRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HelloWorldRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string msg = 1;
  void clear_msg();
  static const int kMsgFieldNumber = 1;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  #if LANG_CXX11
  void set_msg(::std::string&& value);
  #endif
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // @@protoc_insertion_point(class_scope:HelloWorldRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_protoc_2fhello_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class HelloWorldResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:HelloWorldResponse) */ {
 public:
  HelloWorldResponse();
  virtual ~HelloWorldResponse();

  HelloWorldResponse(const HelloWorldResponse& from);

  inline HelloWorldResponse& operator=(const HelloWorldResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HelloWorldResponse(HelloWorldResponse&& from) noexcept
    : HelloWorldResponse() {
    *this = ::std::move(from);
  }

  inline HelloWorldResponse& operator=(HelloWorldResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const HelloWorldResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HelloWorldResponse* internal_default_instance() {
    return reinterpret_cast<const HelloWorldResponse*>(
               &_HelloWorldResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(HelloWorldResponse* other);
  friend void swap(HelloWorldResponse& a, HelloWorldResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HelloWorldResponse* New() const final {
    return CreateMaybeMessage<HelloWorldResponse>(NULL);
  }

  HelloWorldResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<HelloWorldResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const HelloWorldResponse& from);
  void MergeFrom(const HelloWorldResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HelloWorldResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string res = 1;
  void clear_res();
  static const int kResFieldNumber = 1;
  const ::std::string& res() const;
  void set_res(const ::std::string& value);
  #if LANG_CXX11
  void set_res(::std::string&& value);
  #endif
  void set_res(const char* value);
  void set_res(const char* value, size_t size);
  ::std::string* mutable_res();
  ::std::string* release_res();
  void set_allocated_res(::std::string* res);

  // @@protoc_insertion_point(class_scope:HelloWorldResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr res_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_protoc_2fhello_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HelloWorldRequest

// string msg = 1;
inline void HelloWorldRequest::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& HelloWorldRequest::msg() const {
  // @@protoc_insertion_point(field_get:HelloWorldRequest.msg)
  return msg_.GetNoArena();
}
inline void HelloWorldRequest::set_msg(const ::std::string& value) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HelloWorldRequest.msg)
}
#if LANG_CXX11
inline void HelloWorldRequest::set_msg(::std::string&& value) {
  
  msg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:HelloWorldRequest.msg)
}
#endif
inline void HelloWorldRequest::set_msg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HelloWorldRequest.msg)
}
inline void HelloWorldRequest::set_msg(const char* value, size_t size) {
  
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HelloWorldRequest.msg)
}
inline ::std::string* HelloWorldRequest::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:HelloWorldRequest.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HelloWorldRequest::release_msg() {
  // @@protoc_insertion_point(field_release:HelloWorldRequest.msg)
  
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HelloWorldRequest::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:HelloWorldRequest.msg)
}

// -------------------------------------------------------------------

// HelloWorldResponse

// string res = 1;
inline void HelloWorldResponse::clear_res() {
  res_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& HelloWorldResponse::res() const {
  // @@protoc_insertion_point(field_get:HelloWorldResponse.res)
  return res_.GetNoArena();
}
inline void HelloWorldResponse::set_res(const ::std::string& value) {
  
  res_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HelloWorldResponse.res)
}
#if LANG_CXX11
inline void HelloWorldResponse::set_res(::std::string&& value) {
  
  res_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:HelloWorldResponse.res)
}
#endif
inline void HelloWorldResponse::set_res(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  res_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HelloWorldResponse.res)
}
inline void HelloWorldResponse::set_res(const char* value, size_t size) {
  
  res_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HelloWorldResponse.res)
}
inline ::std::string* HelloWorldResponse::mutable_res() {
  
  // @@protoc_insertion_point(field_mutable:HelloWorldResponse.res)
  return res_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HelloWorldResponse::release_res() {
  // @@protoc_insertion_point(field_release:HelloWorldResponse.res)
  
  return res_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HelloWorldResponse::set_allocated_res(::std::string* res) {
  if (res != NULL) {
    
  } else {
    
  }
  res_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), res);
  // @@protoc_insertion_point(field_set_allocated:HelloWorldResponse.res)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_protoc_2fhello_2eproto
