# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('P\001'),
  serialized_pb=_b('\n\x0bhello.proto\" \n\x11HelloWorldRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"!\n\x12HelloWorldResponse\x12\x0b\n\x03res\x18\x01 \x01(\tB\x02P\x01\x62\x06proto3')
)




_HELLOWORLDREQUEST = _descriptor.Descriptor(
  name='HelloWorldRequest',
  full_name='HelloWorldRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='HelloWorldRequest.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=47,
)


_HELLOWORLDRESPONSE = _descriptor.Descriptor(
  name='HelloWorldResponse',
  full_name='HelloWorldResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='HelloWorldResponse.res', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['HelloWorldRequest'] = _HELLOWORLDREQUEST
DESCRIPTOR.message_types_by_name['HelloWorldResponse'] = _HELLOWORLDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloWorldRequest = _reflection.GeneratedProtocolMessageType('HelloWorldRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOWORLDREQUEST,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:HelloWorldRequest)
  ))
_sym_db.RegisterMessage(HelloWorldRequest)

HelloWorldResponse = _reflection.GeneratedProtocolMessageType('HelloWorldResponse', (_message.Message,), dict(
  DESCRIPTOR = _HELLOWORLDRESPONSE,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:HelloWorldResponse)
  ))
_sym_db.RegisterMessage(HelloWorldResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
