// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

public interface HelloWorldRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloWorldRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
